# Generated by Django 4.2.10 on 2024-03-24 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievement",
            name="user",
        ),
        migrations.RemoveField(
            model_name="education",
            name="user",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="user",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="profilelink",
            name="user",
        ),
        migrations.RemoveField(
            model_name="project",
            name="user",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="user",
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="achievement",
            name="resume",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                to="resumes.resume",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="education",
            name="resume",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educations",
                to="resumes.resume",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="experience",
            name="resume",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiences",
                to="resumes.resume",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="resume",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="resumes.resume",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profilelink",
            name="resume",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_links",
                to="resumes.resume",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="resume",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="resumes.resume",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skill",
            name="resume",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="resumes.resume",
            ),
            preserve_default=False,
        ),
    ]
